export const SUCCES_REGISTER='SUCCES_REGISTER'
export const SUCCES_LOGIN='SUCCES_LOGIN'
export const FAIL_REGISTER='FAIL_REGISTER'
export const FAIL_LOGIN='FAIL_LOGIN'
export const SET_ERROR='SET_ERROR'
export const CLEAR_ERROR='CLEAR_ERROR'
export const LOG_OUT='LOG_OUT'
export const SET_USER='SET_USER'
export const AUTH_ERROR='AUTH_ERROR'

